name: qe-lectures
channels:
  - default
  - conda-forge
dependencies:
  - pip
  - python=3.8
  - anaconda=2020.07
  - pip:
    - jupyter-book
    - git+https://github.com/executablebooks/sphinx-multitoc-numbering
    - git+https://github.com/quantecon/quantecon-book-theme
    - git+https://github.com/executablebooks/sphinx-exercise.git
    - quantecon
